services:
  - type: worker
    name: staycharlie-price-monitor
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: MONITOR_URL
        value: https://www.staycharlie.com.br/charlie-nik-pinheiros?city=SP&start_date=2025-09-08&end_date=2025-09-12&guests=1
      - key: CHECK_INTERVAL_MINUTES
        value: 30
      - key: PRICE_THRESHOLD_PERCENT
        value: 5.0
      - key: DISCOUNT_PERCENT
        value: 25.0
